//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oauth_info
    {
        public int ID { get; set; }
        public string oAuthID { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual User_Details User_Details { get; set; }
    }
}
