//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class reaction_info
    {
        public bool isLiked { get; set; }
        public System.DateTime DateOfUpdation { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> BID { get; set; }
    
        public virtual Blog_Detail Blog_Detail { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
